### ISSUE TITLE
ReferenceError: Can't find variable: vegaEmbed

### ISSUE THREAD

**Issue by skovuri41** [joinr/vegafx#1]
Running the example from the Readme gives the following error:

ReferenceError: Can't find variable: vegaEmbed

I will try to debug but in case if i am missing anything obvious.

**Comment by joinr** [comment]
Which example specifically?

Note: if you try to use the GUI menu (denoted by a button with ellipses (...) to the right of the plot),  such as selecting the context menu "save as PNG", this will create a popup window, render the chart's PNG.  It's on my todo to get the vegaembed controls working to support this (by allowing popup windows in webview).  That's the only way I replicated your error (and is currently a known issue).

Preferred means is to just use `vega->image` function.  Please let me know if that caused an error.

**Comment by joinr** [comment]
Please try again.  I just pushed an update that allows popup windows, so the vegaembed controls now work.  You can use them so export PNGs, view source, and view the plot in the vega editor from the webview (as opposed to purely programmatically).

**Comment by skovuri41** [comment]
Still seeing the error as follows:

java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

```
user> (require '[vegafx.core :as vfx])
;; => nil
user> (def test-spec {"$schema" "https://vega.github.io/schema/vega-lite/v2.0.json"
                  "data" {"values" [{"a" "A","b" 100}
                                    {"a" "B","b" 55}
                                    {"a" "C","b" 43}
                                    {"a" "D","b" 91}
                                    {"a" "E","b" 81}
                                    {"a" "F","b" 53}
                                    {"a" "G","b" 19}
                                    {"a" "H","b" 87}
                                    {"a" "I","b" 52}]}
                  "mark" "bar"
                  "encoding" {"x" {"field" "a", "type" "ordinal"}
                              "y" {"field" "b", "type" "quantitative"}}
                  "background" "white"})
;; => #'user/test-spec
user> (vfx/vega->image test-spec "the-image")
Exception in thread "JavaFX Application Thread" netscape.javascript.JSException: ReferenceError: Can't find variable: vegaEmbed
	at com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:128)
	at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at com.sun.webkit.WebPage.executeScript(WebPage.java:1439)
	at javafx.scene.web.WebEngine.executeScript(WebEngine.java:982)
	at vegafx.core$vega_lite$fn$reify__12324.changed(core.clj:179)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
```

**Comment by joinr** [comment]
Hmm, sounds like the vegaEmbed js script isn't getting loaded by webview correctly.  Could be that it's a very old java 1.8 release (there were webview bugs).  Can you try the same example, but emit html?  So use vega->html and open the html in your browser to see if it loads?   It could also be that the connection for the Vega libs isn't working on your end (they're being downloaded still, but I intend to embed them so this should work offline).  A couple of possibilities

**Comment by skovuri41** [comment]
Updated Java also same error. :(
```
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
```

1. vega-html works okay, opened generated html from browser and looks okay.
2. JS files no issue loading from cdn.

**Comment by joinr** [comment]
I replicated this running on ubuntu with openjdk.  My dev system was windows using zulu's openjdk + openjfx 8.  Let's see if it's a linux issue...

**Comment by joinr** [comment]
Yeah, I can't even load the emitted html (with embedded scripts) in a webview directly with .loadContent on linux.

**Comment by joinr** [comment]
Looks like webview on ubuntu using openjfx 8 isn't happy.  Navingating to vega plot examples doesn't work (page won't load).  Embedding the vega scripts directly into the html doesn't work (scripts don't run or otherwise bug out).

I'm thinking this is a problem with OpenJFX 8.  

I'm on openjdk version "1.8.0_222", and on openjfx 8u60 from the packages (running older ubuntu, may try upgrading).  Looks like openjfx 8u161 is available if I can figure out how to install and test it.

I got this working with the openjdk 1.8_202, via the java zulu-fx candidate  "8.0.202-zulufx" in [sdk-man](https://sdkman.io/usage).

I haven't tried with other JDK's yet, but will using SDKman to see if any other 1.8 JDK's are viable.

![demo](https://user-images.githubusercontent.com/4629681/68077000-3b142180-fd8a-11e9-8bd9-098c6c12faf0.png)

**Comment by joinr** [comment]
Just pushed instructions for OpenJDK8/OpenJFX8.  It looks like (based on my experimentation), the only way to support broadly functional Java8 webviews is via the Azul Systems or Bell Software OpenJDK distributions (possibly Oracle's Java8SE if you're willing to get billed....).  The binary distros shipped with ubuntu at least aren't up to snuff.  Zulu looks like a good, stable, known distribution available on all platforms.  Unless someone else discovers something better, it looks like those are the constraints we're working under.

**Comment by skovuri41** [comment]
tried with Oracle Jdk 13 and it works as expected. Oracle JDK8 does not work as you mentioned. thanks.

**Comment by joinr** [comment]
Fyi, I'm working on getting JDK 8 support working headlessley via nashorn.  Currently it looks like vega3 is feasible (render to SVG then target graphics2d via jfreesvg to get an image buffer or png).  Thanks for testing on jdk13, good to know
